[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"

[functions]
  directory = "netlify/functions"

[[functions.cron]]
  function = "fetchForXiaoZhi"
  schedule = "* * * * *" # setiap 1 menit





